# tomcat
server:
  port: 9999
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    # 最大线程数
    max-threads: 1000
    max-http-header-size: 8096
    # 设置tomcat的basedir
    basedir: ${user.home}/tomcat/tmp
    # 最大连接数
    max-connections: 2000

# spring
spring:
  application:
    name: shianxian-supervise
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false # 使用时间戳，使用数值timestamp表示日期
  # 数据库访问配置
  datasource:
    name: ycjg
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.18.10.11:3306/ycjg?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: 1234
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    # 德鲁伊连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true

  # redis
  redis:
    # Redis服务器地址
    host: 10.18.9.250
    # Redis服务器连接端口
    port: 6379
    # 密码
    password: honest1101
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # db
        index: 0
        # 可用的最大连接实例数 默认为8（使用负值表示没有限制）
        max-total: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait-millis: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接最小空闲时间(毫秒)
        min-evictable-idle-time-millis: 1800000
        # 释放连接的扫描间隔（毫秒）
        time-between-eviction-runs-millis: 30000
        # 每次释放连接的最大数目
        num-tests-per-eviction-run: 1024

agora:
  appid: b676a4deb7964ee480fc51c72554c97e
  certificate: 1101
  account: 1101

# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-dev.xml